In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/fasttext-twitter-derived-embeddings/twitter_derived_embeddings
/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/test.csv
/kaggle/input/nlp-getting-started/train.csv


In [2]:
#%%time

#fasttext_embeddings = np.load('../input/pickled-crawl300d2m-for-kernel-competitions/crawl-300d-2M.pkl', allow_pickle=True)

In [3]:
embeddings_df = pd.read_pickle('/kaggle/input/fasttext-twitter-derived-embeddings/twitter_derived_embeddings')
embeddings_df.head()

Token                                         Embeddings
0           aa  [0.06992905, -0.6443515, 0.32829714, -0.420536...
1         aaaa  [-0.29368854, -0.28680354, 0.082138516, -0.093...
2  aaaaaaallll  [0.21100129, -0.24272849, -0.15285794, -0.2225...
3     aaaaaand  [0.15002657, 0.121883154, -0.13981317, 0.04672...
4  aaarrrgghhh  [0.23939471, -0.120745406, -0.023043174, -0.16...

In [4]:
EMBEDDING_DIM = 300

fasttext_embedding_idx = {}
for idx, row in embeddings_df.iterrows():
    word = row[0]
    embeddings = np.asarray(row[1], 'float32')
    fasttext_embedding_idx[word] = embeddings

# print only 20
fasttext_embedding_idx['earthquake'][:20]



array([ 0.36360028,  0.06347924, -0.20796725, -0.1053633 , -0.4619699 ,
       -0.5379099 , -0.24516329, -0.373171  ,  0.55195075, -0.0964388 ,
       -0.02738901, -0.68742454,  0.04655449,  0.31652683, -0.28420547,
        0.32772318, -0.48024014, -0.5669692 ,  0.5986041 , -0.4811064 ],
      dtype=float32)

In [5]:
fasttext_embedding_idx['volcano'][:20]

array([ 0.3942571 , -0.00165699,  0.21576007, -0.6281674 , -0.61796415,
        0.5220277 , -0.10654958, -0.51835054,  0.11060573, -0.45126608,
       -0.65426755, -0.5152729 , -0.17358208,  0.15663569, -0.18588951,
        0.26260749, -0.5199955 , -0.48783213,  0.64488477, -0.32145846],
      dtype=float32)

In [6]:
'''
hyper_params = {"lr": 0.01,
    "epoch": 20,
    "wordNgrams": 2,
    "dim": 20}     
        
# Train the model.
model = fastText.train_supervised(input=training_data_path, **hyper_params)
print("Model trained with the hyperparameter \n {}".format(hyper_params))
'''

'\nhyper_params = {"lr": 0.01,\n    "epoch": 20,\n    "wordNgrams": 2,\n    "dim": 20}     \n        \n# Train the model.\nmodel = fastText.train_supervised(input=training_data_path, **hyper_params)\nprint("Model trained with the hyperparameter \n {}".format(hyper_params))\n'

In [7]:
'''
import fasttext
import fasttext.util
'''

'\nimport fasttext\nimport fasttext.util\n'

In [8]:
#ftmodel = fasttext.train_supervised(input='/kaggle/input/nlp-getting-started/train.csv',label_prefix="__label__",neg=5,epoch=10,dim=300,loss='hs',word_ngrams=2,ws=4,minn=2,maxn=6,pretrainedVectors='/kaggle/input/fasttext-twitter-derived-embeddings/twitter_derived_embeddings')

In [9]:
fasttext_embedding_idx['volcano']

array([ 3.94257098e-01, -1.65699038e-03,  2.15760067e-01, -6.28167391e-01,
       -6.17964149e-01,  5.22027671e-01, -1.06549583e-01, -5.18350542e-01,
        1.10605732e-01, -4.51266080e-01, -6.54267550e-01, -5.15272915e-01,
       -1.73582077e-01,  1.56635687e-01, -1.85889512e-01,  2.62607485e-01,
       -5.19995511e-01, -4.87832129e-01,  6.44884765e-01, -3.21458459e-01,
        2.15166628e-01,  4.63117570e-01,  1.07958339e-01,  2.89399117e-01,
       -2.00538011e-03, -7.02303588e-01,  1.47227183e-01,  8.57290998e-03,
       -2.62118757e-01, -1.99248493e-02, -2.92139560e-01, -6.36468530e-01,
       -1.13391653e-01, -4.46380913e-01, -4.72226202e-01,  6.44273683e-02,
        3.57106954e-01, -3.91963273e-01,  5.86057484e-01, -2.09324867e-01,
       -4.89988290e-02,  1.80484653e-02,  3.29997599e-01, -7.50802904e-02,
        6.11840546e-01, -1.68475494e-01, -5.33606887e-01, -1.96631297e-01,
       -1.74290668e-02,  3.24276417e-01, -2.48807222e-01,  4.34415281e-01,
       -2.90339410e-01,  

In [10]:
tweet = "what is this"
wordlist = tweet.split()
print(wordlist)

['what', 'is', 'this']


In [11]:
embedlist = []
for i in wordlist:
    embedlist.append(fasttext_embedding_idx[i][:10])
print(embedlist)    


[array([ 0.16778643, -0.34444407,  0.6230939 , -0.20073576, -0.34813288,
        0.02173916, -0.11704082,  0.06076448, -0.36336082, -0.00892314],
      dtype=float32), array([-3.5111606e-03, -1.0835886e-02,  4.1052923e-01, -3.4856796e-04,
        2.5777566e-01,  6.7859411e-02, -1.9315183e-02,  7.9721659e-02,
       -1.0232431e-01,  4.5790672e-02], dtype=float32), array([ 0.10859463, -0.21322455,  0.31789047, -0.13303414,  0.08827708,
       -0.24054845, -0.06803452, -0.21234249,  0.32304865,  0.04080255],
      dtype=float32)]
